services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app
      - ./data:/home
    networks:
      - api_net

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: tprli
      POSTGRES_DB: postgresDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api_net 

  cassandra:
    image: cassandra:latest
    restart: unless-stopped
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=tprli
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1536M
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - api_net

  cassandra-replicat-0:
    image: cassandra:latest
    restart: unless-stopped
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=tprli
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-replicat-0
      - CASSANDRA_LISTEN_ADDRESS=cassandra-replicat-0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-replicat-0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra-replicat-0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1536M
    volumes:
      - cassandra_data_0:/var/lib/cassandra
    networks:
      - api_net

  cassandra-replicat-1:
    image: cassandra:latest
    depends_on:
      - cassandra-replicat-0
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-replicat-0
      - CASSANDRA_LISTEN_ADDRESS=cassandra-replicat-1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-replicat-1
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra-replicat-1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1536M
    volumes:
      - cassandra_data_1:/var/lib/cassandra
    networks:
      - api_net

  cassandra-replicat-2:
    image: cassandra:latest
    depends_on:
      - cassandra-replicat-0
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-replicat-0
      - CASSANDRA_LISTEN_ADDRESS=cassandra-replicat-2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-replicat-2
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra-replicat-2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1536M
    volumes:
      - cassandra_data_2:/var/lib/cassandra
    networks:
      - api_net

volumes:
  pgdata:
  cassandra_data:
  cassandra_data_0:
  cassandra_data_1:
  cassandra_data_2:

networks:
  api_net:
    driver: bridge
