services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app
      - ./data:/home
    networks:
      - api_net

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: tprli
      POSTGRES_DB: postgresDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api_net 

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=tprli
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - api_net

volumes:
  pgdata:
  cassandradata:

networks:
  api_net:
    driver: bridge
